---
- name: Healthcheck
  hosts: all
  tasks:
    - action: ping
    - name: Disk usage from command module
            command: df -h
            register: space
          - debug:
                  var: space.stdout_lines