---
- name: Healthcheck
  hosts: all
  tasks:
    - action: ping
      register: pingstate
    - name: Disk usage from command module
        command: df -h
        register: space
        when: pingstate|success
      - debug:
              var: space.stdout_lines